Repository usyd-blockchain/vandal, pull requests merged in 2018-02, with the labels that each got.

#40 Modify the "use" EDB relation to include the argument position
  src/exporter.py
  tools/bulk_analyser/spec.dl
Labels: enhancement

#42 Deterministic stdout output. Resolves #8.
  src/cfg.py
  src/dataflow.py
  src/function.py
  src/memtypes.py
  src/tac_cfg.py
Labels: bug

#41 add byzantinium opcodes
  src/exporter.py
  src/opcodes.py
  test/data/expected/decompile_byzantium-basic.hex.output
  test/data/expected/decompile_byzantium-revert.hex.output
  test/data/expected/decompile_multisig.hex.output
  test/data/expected/decompile_recursion.hex.output
  test/data/expected/disassemble_byzantium-basic.hex.output
  test/data/expected/disassemble_byzantium-revert.hex.output
  test/data/expected/disassemble_pretty_byzantium-basic.hex.output
  test/data/expected/disassemble_pretty_byzantium-revert.hex.output
  test/data/hex/byzantium-basic.hex
  test/data/hex/byzantium-revert.hex
Labels: bug, enhancement
